repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: Fix code format Prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        name: Analize code with ESLint
        additional_dependencies:
          - eslint@8.50.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-import@2.28.1
          - eslint-plugin-prettier@5.0.0
